vagrantfile:
    target: aws
    vm:
        provider:
            aws:
                box: dummy
                machines:
                    vflm_oevdf16x1ev6:
                        id: airq.aws
                        hostname: airq.aws
                        keypair_name: AirQ
                        private_key_path: puphpet/files/dot/ssh/id_rsa
                        ssh_username: ubuntu
                        region: eu-central-1
                        instance_type: t2.micro
                        ami: ami-87564feb
                        subnet_id: subnet-b04377d9
                        elastic_ip: 52.58.166.63
                        security_groups: sg-6e19f106
                        ebs_size: 50
                        ebs_type: gp2
                        ebs_delete_on_termination: false
                        ebs_optimized: false
                        monitoring:
                        associate_public_ip: false
                        package_tags:
                        elb:
                        terminate_on_shutdown: false
                        tags:
                          Name: 'airq server'
                          Project: airq
                synced_folder:
                    vflm_oevdf16x1rdc:
                        source: ./server/conf
                        target: /aws-conf
